/*
# HR Portal — Phase 1.1 Verification & Security Corrections

## Overview
Corrects five issues found during verification of the Phase 1 database foundation.
No frontend files are changed. No business logic is altered.

## Corrections

### 1. profiles → auth.users Foreign Key
Adds a foreign key from profiles.id to auth.users(id) with ON DELETE CASCADE.
Uses NOT VALID so existing seed rows (which don't have auth.users entries yet)
are not checked. New inserts/updates will enforce the constraint once
authentication users are created in Phase 2.

### 2. audit_logs INSERT Policy Tightened
Previous: WITH CHECK (true) — any authenticated user could forge audit records.
New: WITH CHECK (is_hr()) — only HR can insert audit logs via the client API.
Database triggers (added in security-hardening phase) bypass RLS and will
still be able to insert audit records regardless of this policy.

### 3. notifications INSERT Policy Tightened
Previous: user_id = auth.uid() OR is_hr() — employees could create arbitrary
notifications for themselves.
New: is_hr() only — notifications are generated by trusted mechanisms
(database triggers, SECURITY DEFINER functions, or HR administrative action).
Users retain SELECT (own + HR) and UPDATE (own read/unread state) access.

### 4. requests UPDATE Policy Fixed
Previous bug: subquery had `requests_1.id = requests_1.id` (tautology) instead
of `requests_1.id = requests.id` (comparing against the row being updated).
This meant the employee_id lock check was ineffective.
Additional: manager_id, employee_name, and manager_name were not protected.
New: WITH CHECK verifies that managers cannot change employee_id, manager_id,
employee_name, or manager_name during approval/rejection. Only status,
decided_at, and decision_comment may be modified by the assigned manager.

### 5. profiles UPDATE Policy Enhanced
Previous: prevented changing role and manager_id but not employee_number.
New: also prevents changing employee_number. Non-HR users can only update
non-sensitive fields (name, position, department, email, phone, status).

## Important Notes
- No business logic changed: manager_id remains hierarchy source of truth,
  request snapshots preserved, HR cannot approve/reject, managers limited
  to assigned requests.
- No auth users created.
- No frontend files modified.
*/

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. PROFILES → AUTH.USERS FOREIGN KEY
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'profiles_id_auth_users_fkey'
      AND table_name = 'profiles'
  ) THEN
    ALTER TABLE profiles
      ADD CONSTRAINT profiles_id_auth_users_fkey
      FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
      NOT VALID;
  END IF;
END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. AUDIT_LOGS INSERT — restrict to HR only
-- ═══════════════════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS "audit_logs_insert" ON audit_logs;

CREATE POLICY "audit_logs_insert_hr"
  ON audit_logs FOR INSERT
  TO authenticated
  WITH CHECK (is_hr());

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. NOTIFICATIONS INSERT — restrict to HR only
-- ═══════════════════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS "notifications_insert" ON notifications;

CREATE POLICY "notifications_insert_hr"
  ON notifications FOR INSERT
  TO authenticated
  WITH CHECK (is_hr());

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. REQUESTS UPDATE — fix tautology bug + protect snapshot fields
-- ═══════════════════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS "requests_update" ON requests;

CREATE POLICY "requests_update"
  ON requests FOR UPDATE
  TO authenticated
  USING (
    manager_id = auth.uid()
    OR is_hr()
  )
  WITH CHECK (
    -- Managers: cannot change employee_id, manager_id, employee_name, manager_name
    (
      manager_id = auth.uid()
      AND employee_id = (
        SELECT old_req.employee_id FROM requests old_req
        WHERE old_req.id = requests.id
      )
      AND manager_id = (
        SELECT old_req.manager_id FROM requests old_req
        WHERE old_req.id = requests.id
      )
      AND employee_name = (
        SELECT old_req.employee_name FROM requests old_req
        WHERE old_req.id = requests.id
      )
      AND manager_name = (
        SELECT old_req.manager_name FROM requests old_req
        WHERE old_req.id = requests.id
      )
    )
    OR is_hr()
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. PROFILES UPDATE — also protect employee_number
-- ═══════════════════════════════════════════════════════════════════════════

DROP POLICY IF EXISTS "profiles_update_own" ON profiles;

CREATE POLICY "profiles_update_own"
  ON profiles FOR UPDATE
  TO authenticated
  USING (id = auth.uid() OR is_hr())
  WITH CHECK (
    is_hr()
    OR (
      id = auth.uid()
      -- Cannot change role
      AND role = (
        SELECT p.role FROM profiles p WHERE p.id = auth.uid()
      )
      -- Cannot change manager_id
      AND manager_id = (
        SELECT p.manager_id FROM profiles p WHERE p.id = auth.uid()
      )
      -- Cannot change employee_number
      AND employee_number = (
        SELECT p.employee_number FROM profiles p WHERE p.id = auth.uid()
      )
    )
  );
